stages:
    - docker

buildApp:
    stage: docker
    tags: 
        - docker-test
    script:
        - ssh test@192.168.1.1 "ls -a && pwd && echo "hello world""

    rules:
        - if: $CI_COMMIT_BRANCH == "test-use-docker"
        when: manual
