image: node:8.9-alpine

stages:
    - docker
    
buildApp:
    stage: docker
    tags: 
        - test-docker
    script:
        - echo "now we are going to test whether it can show the docker information."
        - docker info
    rules:
        - if: $CI_COMMIT_BRANCH == "test-use-docker"